name: Smoke test Ruby gem
description: Tests Ruby gem installation and functionality

inputs:
  gem-path:
    description: Path to the Ruby gem file or directory containing gems
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Smoke test Ruby gem
      shell: bash
      run: scripts/ci/actions/smoke-ruby/run.sh "${{ inputs.gem-path }}"
