name: Build Ruby gem (Unix)
description: Builds Ruby native gem on Unix platforms (Linux/macOS)

inputs:
  platform:
    description: Ruby platform (e.g., x86_64-linux, arm64-darwin)
    required: true
  build-source-gem:
    description: Whether to also build a source gem
    required: false
    default: "false"

outputs:
  gem-path:
    description: Path to the built native gem
    value: ${{ steps.package.outputs.gem-path }}

runs:
  using: composite
  steps:
    - name: Install Ruby dependencies
      shell: bash
      working-directory: packages/ruby
      run: ../../scripts/ci/actions/build-ruby-unix/install-deps.sh

    - name: Build native gem
      shell: bash
      working-directory: packages/ruby
      env:
        RB_SYS_CARGO_PROFILE: release
      run: ../../scripts/ci/actions/build-ruby-unix/build-native.sh

    - name: Package native gem
      id: package
      shell: bash
      working-directory: packages/ruby
      run: ../../scripts/ci/actions/build-ruby-unix/package.sh

    - name: Build source gem
      if: inputs.build-source-gem == 'true'
      shell: bash
      working-directory: packages/ruby
      run: bundle exec rake build
