self-hosted-runner:
  labels:
    - build-heavy
    - ci-standard
    - benchmark
    - runner-small
    - runner-medium
    - runner-medium-arm64
    - runner-large
    - runner-large-spot
    - runner-medium-arm64-spot
