name: Smoke test Rust crate
description: Tests Rust crate installation and functionality

inputs:
  source-path:
    description: Path to the crate source (defaults to workspace root)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Smoke test Rust crate
      shell: bash
      run: scripts/ci/actions/smoke-rust/run.sh "${{ inputs.source-path }}"
