inherit_from: ../../packages/ruby/.rubocop.yaml

RSpec/PredicateMatcher:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Exclude:
    - 'spec/**/*.rb'
