name: Build Ruby gem (Windows)
description: Builds Ruby native gem on Windows using MSYS2

inputs:
  platform:
    description: Ruby platform (e.g., x64-mingw32)
    required: true

outputs:
  gem-path:
    description: Path to the built native gem
    value: ${{ steps.package.outputs.gem-path }}

runs:
  using: composite
  steps:
    - name: Install MSYS2 toolchain
      shell: pwsh
      run: ridk exec pacman -S --needed --noconfirm base-devel mingw-w64-ucrt-x86_64-toolchain

    - name: Install Rust GNU toolchain
      shell: pwsh
      run: rustup toolchain install stable-gnu --profile minimal --no-self-update

    - name: Configure bindgen sysroot
      shell: bash
      run: echo "BINDGEN_EXTRA_CLANG_ARGS=--target=x86_64-pc-windows-gnu --sysroot=${RI_DEVKIT//\\/\/}$MSYSTEM_PREFIX" >> "$GITHUB_ENV"

    - name: Install Ruby dependencies
      shell: pwsh
      run: scripts/ci/actions/build-ruby-windows/install-deps.ps1

    - name: Build native gem
      shell: pwsh
      env:
        RB_SYS_CARGO_PROFILE: release
      run: scripts/ci/actions/build-ruby-windows/build-native.ps1

    - name: Package native gem
      id: package
      shell: pwsh
      run: scripts/ci/actions/build-ruby-windows/package.ps1
