name: Setup Python Environment
description: Install uv, set up Python, and cache the local virtual environment
inputs:
  python-version:
    description: Python version spec passed to actions/setup-python
    required: true
  cache-prefix:
    description: Prefix for cache keys
    required: false
    default: python-dependencies
outputs:
  python-version:
    description: Resolved Python version
    value: ${{ steps.setup-python.outputs.python-version }}
  cache-hit:
    description: Whether the dependency cache was restored
    value: ${{ steps.cache-python.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Compute uv.lock hash
      id: uv-lock-hash
      shell: bash
      run: scripts/ci/actions/setup-python-env/uv-lock-hash.sh

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache Python dependencies
      id: cache-python
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ inputs.python-version }}-${{ steps.uv-lock-hash.outputs.value }}-v2
        restore-keys: |
          ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ inputs.python-version }}-v2-

    - name: Pin Python version for uv
      shell: bash
      run: scripts/ci/actions/setup-python-env/pin-python.sh "${{ inputs.python-version }}"

    - name: Install Python dependencies
      shell: bash
      run: scripts/ci/actions/setup-python-env/install-deps.sh

    - name: Preserve PKG_CONFIG_PATH for OpenSSL
      shell: bash
      run: scripts/ci/actions/setup-python-env/preserve-pkg-config-path.sh
