#!/usr/bin/env bash
set +e

echo "=========================================="
echo "Kreuzberg Environment Configuration"
echo "=========================================="
echo "Platform: $RUNNER_OS"
echo "Repository Root: ${REPO_ROOT:-<not set>}"
echo ""
echo "=== PKG_CONFIG ==="
echo "PKG_CONFIG_PATH: ${PKG_CONFIG_PATH:-<not set>}"
echo ""
echo "=== Library Paths (Unix) ==="
echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:-<not set>}"
echo "DYLD_LIBRARY_PATH: ${DYLD_LIBRARY_PATH:-<not set>}"
echo "DYLD_FALLBACK_LIBRARY_PATH: ${DYLD_FALLBACK_LIBRARY_PATH:-<not set>}"
echo ""
echo "=== Go cgo (if enabled) ==="
echo "CGO_ENABLED: ${CGO_ENABLED:-<not set>}"
echo "CGO_CFLAGS: ${CGO_CFLAGS:-<not set>}"
echo "CGO_LDFLAGS: ${CGO_LDFLAGS:-<not set>}"
echo ""
echo "=== Additional Paths ==="
echo "TESSDATA_PREFIX: ${TESSDATA_PREFIX:-<not set>}"
echo "KREUZBERG_PDFIUM_PREBUILT: ${KREUZBERG_PDFIUM_PREBUILT:-<not set>}"
echo "ORT_LIB_LOCATION: ${ORT_LIB_LOCATION:-<not set>}"
echo "=========================================="
