name: Build CLI binary
description: Builds standalone Kreuzberg CLI binary for a specified target

inputs:
  target:
    description: Rust target triple (e.g., x86_64-unknown-linux-gnu)
    required: true
  use-cross:
    description: Whether to use cross for cross-compilation
    required: false
    default: "false"

outputs:
  archive-path:
    description: Path to the packaged CLI archive (.tar.gz or .zip)
    value: ${{ steps.package.outputs.archive-path }}

runs:
  using: composite
  steps:
    - name: Build CLI binary
      id: build
      shell: bash
      run: scripts/ci/actions/build-cli/build.sh "${{ inputs.target }}" "${{ inputs.use-cross }}"

    - name: Package CLI archive (Unix)
      id: package
      if: runner.os != 'Windows'
      shell: bash
      run: scripts/ci/actions/build-cli/package-unix.sh "${{ inputs.target }}"

    - name: Package CLI archive (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: scripts/ci/actions/build-cli/package-windows.ps1 "${{ inputs.target }}"
