name: 'Build Wheels'
description: 'Build Python wheels using cibuildwheel'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  linux-archs:
    description: 'Override for CIBW_ARCHS_LINUX'
    required: false
    default: ''
  macos-archs:
    description: 'Override for CIBW_ARCHS_MACOS'
    required: false
    default: ''
  windows-archs:
    description: 'Override for CIBW_ARCHS_WINDOWS'
    required: false
    default: ''
  artifact-name:
    description: 'Custom artifact name for wheel uploads'
    required: false
    default: ''

outputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: wheels-${{ runner.os }}

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Configure Rust lint flags
      shell: bash
      run: scripts/ci/actions/build-wheels/configure-rust-lint-flags.sh

    - name: Setup Python environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ inputs.python-version }}
        cache-prefix: python-build-wheels

    - name: Prepare ONNX Runtime caches
      if: runner.os == 'Linux' || runner.os == 'macOS'
      shell: bash
      run: scripts/ci/actions/build-wheels/prepare-onnx-caches.sh

    - name: Install cibuildwheel
      shell: bash
      run: uv tool install cibuildwheel

    - name: Build wheels
      shell: bash
      run: uvx cibuildwheel packages/python --output-dir wheelhouse
      env:
        CIBW_BUILD: cp310-*

        CIBW_ARCHS_LINUX: ${{ inputs.linux-archs != '' && inputs.linux-archs || 'x86_64 aarch64' }}
        CIBW_ARCHS_MACOS: ${{ inputs.macos-archs != '' && inputs.macos-archs || 'x86_64 arm64' }}
        CIBW_ARCHS_WINDOWS: ${{ inputs.windows-archs != '' && inputs.windows-archs || 'AMD64' }}

        CIBW_BUILD_FRONTEND: "build"
        CIBW_BUILD_VERBOSITY: 1

        CIBW_BEFORE_ALL_LINUX: >
          yum install -y openssl-devel pkgconfig &&
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          source ~/.cargo/env
        CIBW_BEFORE_ALL_MACOS: >
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          source ~/.cargo/env &&
          rustup target add x86_64-apple-darwin aarch64-apple-darwin
        CIBW_BEFORE_ALL_WINDOWS: >
          curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          refreshenv

        CIBW_BEFORE_BUILD_LINUX: bash /project/scripts/ci/actions/build-wheels/cibw-before-build-linux.sh
        CIBW_BEFORE_BUILD_MACOS: bash scripts/ci/actions/build-wheels/cibw-before-build-macos.sh
        CIBW_BEFORE_BUILD_WINDOWS: >
          python -m pip install --upgrade pip maturin build

        CIBW_ENVIRONMENT: MATURIN_BUILD_ARGS="--compatibility linux"
        CIBW_ENVIRONMENT_WINDOWS: MATURIN_BUILD_ARGS=""
        CIBW_ENVIRONMENT_MACOS: 'MATURIN_BUILD_ARGS="" MACOSX_DEPLOYMENT_TARGET=14.0'

        CIBW_SKIP: "*-win32 *-manylinux_i686"

        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
        CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
        CIBW_MUSLLINUX_X86_64_IMAGE: musllinux_1_2
        CIBW_MUSLLINUX_AARCH64_IMAGE: musllinux_1_2

        CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
        CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: ""

    - name: Upload wheels
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.artifact-name != '' && inputs.artifact-name || format('wheels-{0}', runner.os) }}
        path: ./wheelhouse/*.whl
        retention-days: 7
