name: Cache and Prefetch Hugging Face models for fastembed
description: Cache Hugging Face model directories and optionally prefetch common fastembed models
inputs:
  cache-key-suffix:
    description: Cache key suffix to differentiate model sets
    required: false
    default: fastembed-v1
  fastembed-version:
    description: fastembed crate version to use for prefetch
    required: false
    default: "5.3"
  models:
    description: Comma-separated list of fastembed models to prefetch (use 'default' for the default model)
    required: false
    default: "default,AllMiniLML6V2Q,BGEBaseENV15"
  prefetch:
    description: Whether to pre-download models
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Cache Hugging Face models
      uses: actions/cache@v5
      with:
        path: |
          ~/.cache/huggingface
          ~/Library/Caches/huggingface
          ~\AppData\Local\huggingface
        key: hf-models-v2-${{ runner.os }}-${{ runner.arch }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          hf-models-v2-${{ runner.os }}-${{ runner.arch }}-
          hf-models-v2-${{ runner.os }}-

    - name: Prefetch fastembed models
      if: inputs.prefetch == 'true'
      shell: bash
      env:
        FASTEMBED_VERSION: ${{ inputs.fastembed-version }}
        MODELS: ${{ inputs.models }}
      run: scripts/ci/actions/cache-hf-fastembed/prefetch.sh
