name: Build Rust FFI Library
description: Build Rust FFI library (kreuzberg-ffi or language-specific FFI bindings) with proper flags and error handling

inputs:
  crate-name:
    description: 'Name of the Rust crate to build (e.g., kreuzberg-ffi, kreuzberg-py, kreuzberg-node, kreuzberg-rb)'
    required: true
  features:
    description: 'Cargo features to enable (comma-separated, optional)'
    required: false
    default: ''
  target:
    description: 'Rust target triple (optional, defaults to host)'
    required: false
    default: ''
  build-profile:
    description: 'Build profile (release or dev)'
    required: false
    default: 'release'
  verbose:
    description: 'Enable verbose build output'
    required: false
    default: 'true'
  additional-flags:
    description: 'Additional cargo build flags (optional)'
    required: false
    default: ''

outputs:
  library-path:
    description: 'Path to the built library'
    value: ${{ steps.build.outputs.library-path }}
  target-dir:
    description: 'Cargo target directory'
    value: ${{ steps.build.outputs.target-dir }}

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      env:
        CRATE_NAME: ${{ inputs.crate-name }}
        FEATURES: ${{ inputs.features }}
        TARGET: ${{ inputs.target }}
        BUILD_PROFILE: ${{ inputs.build-profile }}
        VERBOSE: ${{ inputs.verbose }}
        ADDITIONAL_FLAGS: ${{ inputs.additional-flags }}
      run: scripts/ci/actions/build-rust-ffi/validate-inputs.sh

    - name: Build FFI library
      id: build
      shell: bash
      env:
        CRATE_NAME: ${{ inputs.crate-name }}
        FEATURES: ${{ inputs.features }}
        TARGET: ${{ inputs.target }}
        BUILD_PROFILE: ${{ inputs.build-profile }}
        VERBOSE: ${{ inputs.verbose }}
        ADDITIONAL_FLAGS: ${{ inputs.additional-flags }}
      run: scripts/ci/actions/build-rust-ffi/build.sh

    - name: Verify build artifacts
      shell: bash
      env:
        LIBRARY_PATH: ${{ steps.build.outputs.library-path }}
        TARGET_DIR: ${{ steps.build.outputs.target-dir }}
      run: scripts/ci/actions/build-rust-ffi/verify.sh
