name: Setup Kreuzberg Environment
description: >
  Configure native library paths for Kreuzberg across all platforms
  (PDFium, ONNX Runtime, Rust FFI, Go cgo).
  Exports environment variables to $GITHUB_ENV for persistence across steps.

inputs:
  mode:
    description: Setup mode - 'full' (all libraries) or 'minimal' (FFI only)
    required: false
    default: 'full'
  enable-cgo:
    description: Enable Go cgo compilation environment setup
    required: false
    default: 'false'
  ffi-lib-dir:
    description: Path to Rust FFI library directory (default is target/release)
    required: false
    default: 'target/release'

outputs:
  pkg-config-path:
    description: PKG_CONFIG_PATH for kreuzberg-ffi
    value: ${{ steps.setup-unix.outputs.pkg-config-path }}
  ld-library-path:
    description: LD_LIBRARY_PATH for Unix-like systems
    value: ${{ steps.setup-unix.outputs.ld-library-path }}

runs:
  using: composite
  steps:
    - name: Determine platform
      id: platform
      shell: bash
      run: scripts/ci/actions/setup-kreuzberg-env/determine-platform.sh

    - name: Setup library paths (Unix-like)
      if: runner.os != 'Windows'
      id: setup-unix
      shell: bash
      run: scripts/ci/actions/setup-kreuzberg-env/setup-unix.sh "${{ inputs.mode }}" "${{ inputs.ffi-lib-dir }}"

    - name: Setup library paths (Windows)
      if: runner.os == 'Windows'
      id: setup-windows
      shell: pwsh
      run: scripts/ci/actions/setup-kreuzberg-env/setup-windows.ps1 -Mode "${{ inputs.mode }}" -FfiLibDir "${{ inputs.ffi-lib-dir }}"

    - name: Setup Go cgo environment (Unix-like)
      if: runner.os != 'Windows' && inputs.enable-cgo == 'true'
      shell: bash
      run: scripts/ci/actions/setup-kreuzberg-env/setup-cgo-unix.sh "${{ inputs.ffi-lib-dir }}"

    - name: Setup Go cgo environment (Windows)
      if: runner.os == 'Windows' && inputs.enable-cgo == 'true'
      shell: pwsh
      run: scripts/ci/actions/setup-kreuzberg-env/setup-cgo-windows.ps1 -FfiLibDir "${{ inputs.ffi-lib-dir }}"

    - name: Verify library paths
      shell: bash
      run: scripts/ci/actions/setup-kreuzberg-env/verify.sh
