name: Setup Go CGO Environment
description: >
  Configure Go cgo compilation and runtime environment for linking against
  Kreuzberg FFI library. Sets PKG_CONFIG_PATH, library paths, CGO_LDFLAGS
  with rpath, and CGO_ENABLED. Handles Windows GNU target specially.

inputs:
  ffi-lib-dir:
    description: Path to Rust FFI library directory (default is target/release)
    required: false
    default: 'target/release'
  enable-rpath:
    description: Add rpath (-Wl,-rpath,...) to CGO_LDFLAGS for runtime library resolution
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Go cgo environment (Unix-like)
      if: runner.os != 'Windows'
      shell: bash
      run: scripts/ci/actions/setup-go-cgo-env/unix.sh "${{ inputs.ffi-lib-dir }}" "${{ inputs.enable-rpath }}"

    - name: Setup Go cgo environment (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: scripts/ci/actions/setup-go-cgo-env/windows.ps1 "${{ inputs.ffi-lib-dir }}"

    - name: Verify Go cgo configuration
      shell: bash
      run: scripts/ci/actions/setup-go-cgo-env/verify.sh "${{ inputs.ffi-lib-dir }}"
