name: Smoke test Node package
description: Tests Node.js package installation and functionality

inputs:
  package-tarball:
    description: Path to the Node.js package tarball
    required: true

runs:
  using: composite
  steps:
    - name: Smoke Node install
      shell: bash
      run: scripts/ci/actions/smoke-node/run.sh "${{ inputs.package-tarball }}"
