name: Smoke test Node package
description: Tests Node.js package installation and functionality

inputs:
  package-tarball:
    description: Path to the Node.js package tarball
    required: true

runs:
  using: composite
  steps:
    - name: Smoke Node install
      shell: bash
      run: |
        set -euo pipefail
        # Make Pdfium and ONNX Runtime available to the native module if downloaded earlier
        if [[ -n "${KREUZBERG_PDFIUM_PREBUILT:-}" ]]; then
          case "${RUNNER_OS:-unknown}" in
            Linux)
              export LD_LIBRARY_PATH="$KREUZBERG_PDFIUM_PREBUILT/lib:${LD_LIBRARY_PATH:-}"
              ;;
            macOS)
              export DYLD_LIBRARY_PATH="$KREUZBERG_PDFIUM_PREBUILT/lib:${DYLD_LIBRARY_PATH:-}"
              ;;
            Windows)
              export PATH="$KREUZBERG_PDFIUM_PREBUILT/bin;${PATH:-}"
              ;;
          esac
        fi
        # ONNX Runtime paths should already be set by setup-onnx-runtime action
        # ORT_LIB_LOCATION, LD_LIBRARY_PATH/DYLD_LIBRARY_PATH are already in env
        tarball="${{ inputs.package-tarball }}"
        # If directory provided, find the tarball inside
        if [[ -d "$tarball" ]]; then
          tarball=$(find "$tarball" -name "*.tgz" -type f | head -n 1)
          if [[ -z "$tarball" ]]; then
            echo "No .tgz file found in directory" >&2
            exit 1
          fi
        fi
        # Convert to absolute path before changing directories
        if [[ "$tarball" != /* ]]; then
          tarball="${GITHUB_WORKSPACE}/$tarball"
        fi
        echo "Using tarball: $tarball"
        tmp=$(mktemp -d)
        cp -R e2e/smoke/node/. "$tmp"/
        pushd "$tmp" >/dev/null
        cp "$tarball" ./kreuzberg-node.tgz

        # Copy kreuzberg-node package to temp dir
        cp -R "${GITHUB_WORKSPACE}/crates/kreuzberg-node" ./kreuzberg-node-pkg

        # Update kreuzberg-node package.json to use the tarball
        node -e "
          const fs = require('fs');
          const path = require('path');

          // Update kreuzberg-node package dependencies to use local tarball
          const pkg = JSON.parse(fs.readFileSync('kreuzberg-node-pkg/package.json', 'utf8'));
          // The native module is already included in the tarball, so we just need to use it
          fs.writeFileSync('kreuzberg-node-pkg/package.json', JSON.stringify(pkg, null, 2) + '\n');

          // Update smoke test package.json to use local kreuzberg-node package
          const smokePkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          if (!smokePkg.dependencies) {
            smokePkg.dependencies = {};
          }
          smokePkg.dependencies['@kreuzberg/node'] = 'file:./kreuzberg-node-pkg';
          fs.writeFileSync('package.json', JSON.stringify(smokePkg, null, 2) + '\n');
        "

        # Build the TypeScript SDK
        pushd kreuzberg-node-pkg >/dev/null
        pnpm install --no-frozen-lockfile
        pnpm build:ts
        popd >/dev/null

        rm -f pnpm-lock.yaml
        pnpm install --no-frozen-lockfile
        pnpm run check
        popd >/dev/null
        echo "✓ Node package smoke test passed"
