name: Verify PDFium Bundled
description: Verify that PDFium runtime libraries are present in package artifacts

inputs:
  package-type:
    description: 'Package type: python-wheel, node-native, ruby-gem, java-jar, go-archive, cli-archive, csharp-nupkg'
    required: true
  artifact-path:
    description: 'Path to package artifact to verify'
    required: true
  platform:
    description: 'Target platform: linux, macos, windows'
    required: true
  expect-bundled:
    description: 'Whether to expect bundled PDFium (true) or no bundled PDFium/static (false)'
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Verify PDFium
      shell: bash
      run: |
        package_type="${{ inputs.package-type }}"
        artifact_path="${{ inputs.artifact-path }}"
        platform="${{ inputs.platform }}"
        expect_bundled="${{ inputs.expect-bundled }}"

        case "$platform" in
          linux) lib_name="libpdfium.so" ;;
          macos) lib_name="libpdfium.dylib" ;;
          windows) lib_name="pdfium.dll" ;;
          *) echo "ERROR: Unknown platform $platform"; exit 1 ;;
        esac

        found=false

        case "$package_type" in
          python-wheel)
            # Python uses static linking - should NOT have bundled PDFium
            if unzip -l "$artifact_path" 2>/dev/null | grep -q "$lib_name"; then
              echo "ERROR: Found $lib_name in Python wheel (should be statically linked)"
              exit 1
            fi
            echo "✓ Python wheel correctly uses static linking (no bundled PDFium)"
            ;;

          node-native)
            # Check if .node file exists and is reasonably sized
            if [ -f "$artifact_path" ]; then
              size=$(stat -f%z "$artifact_path" 2>/dev/null || stat -c%s "$artifact_path")
              if [ "$size" -lt 1000000 ]; then
                echo "ERROR: .node file too small ($size bytes), likely missing PDFium"
                exit 1
              fi
              echo "✓ Node native module is $size bytes (PDFium embedded)"
            fi
            ;;

          ruby-gem)
            # Extract and check for PDFium
            temp_dir=$(mktemp -d)
            tar -xzf "$artifact_path" -C "$temp_dir" data.tar.gz 2>/dev/null || true
            if [ -f "$temp_dir/data.tar.gz" ]; then
              tar -xzf "$temp_dir/data.tar.gz" -C "$temp_dir"
              if find "$temp_dir" -name "$lib_name" | grep -q .; then
                found=true
              fi
            fi
            rm -rf "$temp_dir"

            if [ "$expect_bundled" = "true" ] && [ "$found" = "false" ]; then
              echo "ERROR: $lib_name not found in Ruby gem"
              exit 1
            fi
            echo "✓ Ruby gem verification passed"
            ;;

          java-jar)
            if unzip -l "$artifact_path" | grep -q "$lib_name"; then
              found=true
            fi
            if [ "$expect_bundled" = "true" ] && [ "$found" = "false" ]; then
              echo "ERROR: $lib_name not found in Java JAR"
              exit 1
            fi
            echo "✓ Java JAR verification passed"
            ;;

          cli-archive|go-archive)
            temp_dir=$(mktemp -d)
            if [[ "$artifact_path" == *.tar.gz ]]; then
              tar -xzf "$artifact_path" -C "$temp_dir"
            elif [[ "$artifact_path" == *.zip ]]; then
              unzip -q "$artifact_path" -d "$temp_dir"
            fi

            if find "$temp_dir" -name "$lib_name" | grep -q .; then
              lib_path=$(find "$temp_dir" -name "$lib_name" | head -1)
              size=$(stat -f%z "$lib_path" 2>/dev/null || stat -c%s "$lib_path")
              if [ "$size" -lt 5000000 ]; then
                echo "ERROR: $lib_name too small ($size bytes), likely corrupt"
                exit 1
              fi
              echo "✓ Found $lib_name ($size bytes)"
              found=true
            fi
            rm -rf "$temp_dir"

            if [ "$expect_bundled" = "true" ] && [ "$found" = "false" ]; then
              echo "ERROR: $lib_name not found in archive"
              exit 1
            fi
            ;;

          *) echo "ERROR: Unknown package type $package_type"; exit 1 ;;
        esac
