name: Smoke test CLI binary
description: Tests Kreuzberg CLI binary installation and functionality

inputs:
  cli-artifacts-dir:
    description: Directory containing CLI binary artifacts
    required: true

runs:
  using: composite
  steps:
    - name: Smoke test CLI binary
      shell: bash
      run: scripts/ci/actions/smoke-cli/run.sh "${{ inputs.cli-artifacts-dir }}"
