// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang wasm-deno

// Tests for xml fixtures. Run with: deno test --allow-read

import type { ExtractionResult } from "./helpers.ts";
import { assertions, buildConfig, extractBytes, initWasm, resolveDocument, shouldSkipFixture } from "./helpers.ts";

// Initialize WASM module once at module load time
await initWasm();

Deno.test("xml_plant_catalog", { permissions: { read: true } }, async () => {
	const config = buildConfig(undefined);
	let result: ExtractionResult | null = null;
	try {
		const documentBytes = await resolveDocument("xml/plant_catalog.xml");
		// Sync file extraction - WASM uses extractBytes with pre-read bytes
		result = await extractBytes(documentBytes, "application/xml", config);
	} catch (error) {
		if (shouldSkipFixture(error, "xml_plant_catalog", [], undefined)) {
			return;
		}
		throw error;
	}
	if (result === null) {
		return;
	}
	assertions.assertExpectedMime(result, ["application/xml"]);
	assertions.assertMinContentLength(result, 100);
});
