name: Checkout Target Commit
description: Checkout code and optionally ensure specific commit

inputs:
  checkout_ref:
    description: Git ref to checkout (branch, tag, or commit SHA)
    required: true
  target_sha:
    description: Specific commit SHA to ensure checkout (optional, only enforced if provided)
    required: false
    default: ""
  fetch_depth:
    description: Depth of commit history to fetch
    required: false
    default: "0"
  submodules:
    description: Submodule checkout mode (disable, shallow, or recursive)
    required: false
    default: "recursive"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.checkout_ref }}
        fetch-depth: ${{ inputs.fetch_depth }}
        submodules: ${{ inputs.submodules }}

    - name: Ensure target commit
      if: ${{ inputs.target_sha != '' }}
      shell: bash
      run: scripts/ci/actions/checkout-target-commit/ensure-target-sha.sh "${{ inputs.target_sha }}"
