name: Cleanup Rust Cache
description: Remove large build artifacts to reduce cache size before saving
runs:
  using: composite
  steps:
    - name: Cleanup build artifacts
      shell: bash
      run: scripts/ci/actions/cleanup-rust-cache/cleanup.sh
