name: Setup Prebuilt ONNX Runtime
description: Download prebuilt ONNX Runtime static libraries for Apple targets
inputs:
  target:
    description: Target triple determining which archive to download
    required: true
runs:
  using: composite
  steps:
    - name: Prepare ONNX Runtime archive
      shell: bash
      run: scripts/ci/actions/setup-prebuilt-onnx/prepare.sh "${{ inputs.target }}"
